language: node_js
    
git:
  depth: 3

script: true

before_deploy: scripts/travis-before_deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: /tmp/deploy/travis-deploy.sh
  on:
    branch: master
